import { writable } from 'svelte/store';

export const images = writable<{ link: string; id: string }[]>([
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) },
	// { link: 'https://i.imgur.com/ZgUXcG4.png', id: '' + Math.floor(Math.random() * 9e9) }
]);
